# Generated by Django 3.1.3 on 2020-11-09 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30)),
                ('actor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crisis.actor')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('color', models.CharField(max_length=10)),
                ('responsible_actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crisis.actor')),
            ],
        ),
        migrations.CreateModel(
            name='Team_actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crisis.actor')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crisis.team')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lattitude', models.FloatField()),
                ('longtitude', models.FloatField()),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('phone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crisis.device')),
            ],
        ),
    ]
